### ISSUE TITLE
Inserting a quote hangs Emacs

### ISSUE THREAD

**Issue by jorgenschaefer** [Fuco1/smartparens#440]
Reproduction case:

```Python
import unittest


class TestInit(unittest.TestCase):
    def setUp(self):
        self.bot = bot.Bot("jid", "password", ")
```

Move point to the last `"` on the last line, hit `"`, have Emacs hang. Backtrace from `toggle-debug-on-quit`:

```
Debugger entered--Lisp error: (quit)
  syntax-ppss(125)
  sp-point-in-string(125)
  sp-point-in-string-or-comment(125)
  sp-get-paired-expression(nil)
  sp-get-expression(nil)
  sp-get-sexp()
  #[nil "\301\302!\210\303c\210\304 \301\302!\210^Hc\210\207" [last delete-char$
  sp-skip-closing-pair()
  ad-Advice-self-insert-command(#<subr self-insert-command> 1)
  apply(ad-Advice-self-insert-command #<subr self-insert-command> 1)
  self-insert-command(1)
  sp--self-insert-command(1)
  funcall-interactively(sp--self-insert-command 1)
  call-interactively(sp--self-insert-command nil nil)
  command-execute(sp--self-insert-command)
```

Incidentally, I do not know how, but I ended up with that line by just typing a normal line. It somhow managed to end up with `"password""` with point between the last two quotation marks.

**Comment by andreas-roehler** [comment]
No hang here with this example. Fixed?

**Comment by Fuco1** [comment]
Doesn't hang on master but hangs on the stable release.  Quotes are still a major problem and PITA.

**Comment by andreas-roehler** [comment]
Suggest to close when fixed in master. So people might care for existing bugs.

**Comment by Fuco1** [comment]
The issue is still not fixed, it is just hidden.

You can safely assume all issues with a milestone tag are *not* fixed.

**Comment by manuel-uberti** [comment]
Any progress on this one?

**Comment by Fuco1** [comment]
When before the ", two quotes are inserted, that is correct but not smart behaviour (we are not in a string so we try to make a new one balanced, however, the unclosed quote could be used as a closer instead.

When after the ", one quote is inserted to close the string up.  Works the same with both the regular and strict modes.

The first behaviour should be rectified somehow but that is not what this issue is about.  The problem is now solved on 1.7.*.

**Comment by manuel-uberti** [comment]
Thank you :)
