### ISSUE TITLE
Error running timer ‘sp-show--pair-function’: (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by swarnendubiswas** [Fuco1/smartparens#697]
I have started experiencing this error with Emacs built from git. I am on CentOS 7, and my `smartparens` configuration is as follows:

```
(use-package smartparens
  :ensure t
  :init
  (smartparens-global-mode 1)
  (show-smartparens-global-mode 1)
  :config
  (setq sp-show-pair-from-inside t)
  (sp-pair "(" nil :unless '(sp-point-before-word-p))
  (sp-pair "[" nil :unless '(sp-point-before-word-p))
  (sp-pair "{" nil :unless '(sp-point-before-word-p))
  (sp-local-pair 'latex-mode "$" nil :unless '(sp-point-before-word-p))
  :bind (("C-M-a" . sp-beginning-of-sexp)
         ("C-M-e" . sp-end-of-sexp)
         ("C-M-u" . sp-up-sexp)
         ("C-M-w" . sp-down-sexp)
         ("C-M-f" . sp-forward-sexp)
         ("C-M-b" . sp-backward-sexp)
         ("C-M-n" . sp-next-sexp)
         ("C-M-p" . sp-previous-sexp)
         ("C-S-b" . sp-backward-symbol)
         ("C-S-f" . sp-forward-symbol)
         ("C-M-k" . sp-splice-sexp))
  :diminish smartparens-mode)
```

**Comment by Fuco1** [comment]
Thanks for the report!

Could you please enable debug on error (`M-x toggle-debug-on-error`) and try to capture the trace? It would help a lot with the debugging.

**Comment by swarnendubiswas** [comment]
Sure, I will work on it.

**Comment by swarnendubiswas** [comment]
I haven't seen the error since then. Maybe the more recent updates fixed it? I am not sure.

**Comment by Fuco1** [comment]
Unlikely unless you had some *reaaaaally* old version.  The show mode code is updated very rarely.  Maybe it was an upstream issue which was fixed (emacs git), not sure.

**Comment by swarnendubiswas** [comment]
I think your hunch is right. I see the error on another machine where I haven't updated Emacs from git recently. Here is the output with `M-x toggle-debug-on-error`.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`\\<" nil nil)
  #[(string) "\302\303\304\305#)\266\203\205\304\306\303\304\305#)\266\203\205\"\304D\207" [string inhibit-changing-match-data "\\`\\<" nil t string-match "\\>\\'"] 8](nil)
  -group-by(#[(string) "\302\303\304\305#)\266\203\205\304\306\303\304\305#)\266\203\205\"\304D\207" [string inhibit-changing-match-data "\\`\\<" nil t string-match "\\>\\'"] 8] ("\\\\)" "\\)" "\\}" nil "}" "]" ")"))
  sp--strict-regexp-opt(("\\\\)" "\\)" "\\}" nil "}" "]" ")"))
  sp--get-closing-regexp((("\\\\(" . "\\\\)") ("\\(" . "\\)") ("\\{" . "\\}") ("$") ("{" . "}") ("[" . "]") ("(" . ")")))
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])
```

I am currently updating Emacs from git, hopefully the error will go away.

**Comment by swarnendubiswas** [comment]
I updated Emacs from git on the second machine as I have mentioned earlier, but the error persists. 
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`\\<" nil nil)
  #[(string) "\302\303\304\305#)\266\203\205\304\306\303\304\305#)\266\203\205\"\304D\207" [string inhibit-changing-match-data "\\`\\<" nil t string-match "\\>\\'"] 8](nil)
  -group-by(#[(string) "\302\303\304\305#)\266\203\205\304\306\303\304\305#)\266\203\205\"\304D\207" [string inhibit-changing-match-data "\\`\\<" nil t string-match "\\>\\'"] 8] ("\\\\)" "\\)" "\\}" nil "}" "]" ")"))
  sp--strict-regexp-opt(("\\\\)" "\\)" "\\}" nil "}" "]" ")"))
  sp--get-closing-regexp((("\\\\(" . "\\\\)") ("\\(" . "\\)") ("\\{" . "\\}") ("$") ("{" . "}") ("[" . "]") ("(" . ")")))
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])
```

**Comment by natezb** [comment]
I'm having a similar issue. I'm running Emacs 25.1.1 (via Spacemacs), and I get the following debug output:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`\\<" nil nil)
  string-match-p("\\`\\<" nil)
  (and (string-match-p "\\`\\<" string) t)
  (list (and (string-match-p "\\`\\<" string) t) (and (string-match-p "\\>\\'" string) t))
  (lambda (string) (list (and (string-match-p "\\`\\<" string) t) (and (string-match-p "\\>\\'" string) t)))(nil)
  -group-by((lambda (string) (list (and (string-match-p "\\`\\<" string) t) (and (string-match-p "\\>\\'" string) t))) ("\\\\)" "\\)" "\\}" nil nil))
  (mapconcat (function (lambda (g) (apply (quote sp--regexp-for-group) g))) (-group-by (function (lambda (string) (list (and (string-match-p "\\`\\<" string) t) (and (string-match-p "\\>\\'" string) t)))) strings) "\\|")
  (concat "\\(?:" (mapconcat (function (lambda (g) (apply (quote sp--regexp-for-group) g))) (-group-by (function (lambda (string) (list (and (string-match-p "\\`\\<" string) t) (and (string-match-p "\\>\\'" string) t)))) strings) "\\|") "\\)")
  (progn (set-syntax-table (let ((table (make-syntax-table (syntax-table)))) (modify-syntax-entry 39 "." table) table)) (concat "\\(?:" (mapconcat (function (lambda (g) (apply (quote sp--regexp-for-group) g))) (-group-by (function (lambda (string) (list (and ... t) (and ... t)))) strings) "\\|") "\\)"))
  (unwind-protect (progn (set-syntax-table (let ((table (make-syntax-table (syntax-table)))) (modify-syntax-entry 39 "." table) table)) (concat "\\(?:" (mapconcat (function (lambda (g) (apply (quote sp--regexp-for-group) g))) (-group-by (function (lambda (string) (list ... ...))) strings) "\\|") "\\)")) (save-current-buffer (set-buffer buffer) (set-syntax-table table)))
  (let ((table (syntax-table)) (buffer (current-buffer))) (unwind-protect (progn (set-syntax-table (let ((table (make-syntax-table ...))) (modify-syntax-entry 39 "." table) table)) (concat "\\(?:" (mapconcat (function (lambda (g) (apply ... g))) (-group-by (function (lambda ... ...)) strings) "\\|") "\\)")) (save-current-buffer (set-buffer buffer) (set-syntax-table table))))
  (if strings (let ((table (syntax-table)) (buffer (current-buffer))) (unwind-protect (progn (set-syntax-table (let ((table ...)) (modify-syntax-entry 39 "." table) table)) (concat "\\(?:" (mapconcat (function (lambda ... ...)) (-group-by (function ...) strings) "\\|") "\\)")) (save-current-buffer (set-buffer buffer) (set-syntax-table table)))) "")
  sp--strict-regexp-opt(("\\\\)" "\\)" "\\}" nil nil))
  (progn (if --cl-rest-- (signal (quote wrong-number-of-arguments) (list (quote sp--get-closing-regexp) (+ 1 (length --cl-rest--))))) (sp--strict-regexp-opt (mapcar (function (lambda (it) (cdr it))) pair-list)))
  (let* ((pair-list (if --cl-rest-- (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) (sp--get-pair-list)))) (progn (if --cl-rest-- (signal (quote wrong-number-of-arguments) (list (quote sp--get-closing-regexp) (+ 1 (length --cl-rest--))))) (sp--strict-regexp-opt (mapcar (function (lambda (it) (cdr it))) pair-list))))
  sp--get-closing-regexp((("\\\\(" . "\\\\)") ("\\(" . "\\)") ("\\{" . "\\}") ("(") ("[")))
  (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside (sp--get-allowed-regexp))) match) (cond ((and (not (sp--evil-normal-state-p)) (not (sp--evil-motion-state-p)) (not (sp--evil-visual-state-p)) (sp--looking-back (if sp-show-pair-from-inside allowed closing))) (funcall --cl-scan-and-place-overlays-- (match-string 0) :back)) ((or (and (or (sp--evil-normal-state-p) (sp--evil-motion-state-p) (sp--evil-visual-state-p)) (sp--looking-at (sp--get-allowed-regexp))) (sp--looking-at (if sp-show-pair-from-inside allowed opening)) (looking-at (sp--get-stringlike-regexp)) (and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<"))) (funcall --cl-scan-and-place-overlays-- (match-string 0))) ((or (sp--looking-back (if sp-show-pair-from-inside allowed closing)) (sp--looking-back (sp--get-stringlike-regexp)) (and (memq major-mode sp-navigate-consider-sgml-tags) (sp--looking-back ">"))) (funcall --cl-scan-and-place-overlays-- (match-string 0) :back)) (sp-show-pair-overlays (sp-show--pair-delete-overlays))))
  (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- (function (lambda (match &optional back) (let ((ok (sp-get-thing back))) (if ok (let (...) (if ... ...)) (if back (sp-show--pair-create-mismatch-overlay ... ...) (sp-show--pair-create-mismatch-overlay ... ...))))))) (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside (sp--get-allowed-regexp))) match) (cond ((and (not (sp--evil-normal-state-p)) (not (sp--evil-motion-state-p)) (not (sp--evil-visual-state-p)) (sp--looking-back (if sp-show-pair-from-inside allowed closing))) (funcall --cl-scan-and-place-overlays-- (match-string 0) :back)) ((or (and (or (sp--evil-normal-state-p) (sp--evil-motion-state-p) (sp--evil-visual-state-p)) (sp--looking-at (sp--get-allowed-regexp))) (sp--looking-at (if sp-show-pair-from-inside allowed opening)) (looking-at (sp--get-stringlike-regexp)) (and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<"))) (funcall --cl-scan-and-place-overlays-- (match-string 0))) ((or (sp--looking-back (if sp-show-pair-from-inside allowed closing)) (sp--looking-back (sp--get-stringlike-regexp)) (and (memq major-mode sp-navigate-consider-sgml-tags) (sp--looking-back ">"))) (funcall --cl-scan-and-place-overlays-- (match-string 0) :back)) (sp-show-pair-overlays (sp-show--pair-delete-overlays)))))
  (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- (function (lambda (match &optional back) (let ((ok ...)) (if ok (let ... ...) (if back ... ...)))))) (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside (sp--get-allowed-regexp))) match) (cond ((and (not (sp--evil-normal-state-p)) (not (sp--evil-motion-state-p)) (not (sp--evil-visual-state-p)) (sp--looking-back (if sp-show-pair-from-inside allowed closing))) (funcall --cl-scan-and-place-overlays-- (match-string 0) :back)) ((or (and (or ... ... ...) (sp--looking-at ...)) (sp--looking-at (if sp-show-pair-from-inside allowed opening)) (looking-at (sp--get-stringlike-regexp)) (and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<"))) (funcall --cl-scan-and-place-overlays-- (match-string 0))) ((or (sp--looking-back (if sp-show-pair-from-inside allowed closing)) (sp--looking-back (sp--get-stringlike-regexp)) (and (memq major-mode sp-navigate-consider-sgml-tags) (sp--looking-back ">"))) (funcall --cl-scan-and-place-overlays-- (match-string 0) :back)) (sp-show-pair-overlays (sp-show--pair-delete-overlays))))))
  (unwind-protect (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- (function (lambda (match &optional back) (let (...) (if ok ... ...))))) (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside (sp--get-allowed-regexp))) match) (cond ((and (not ...) (not ...) (not ...) (sp--looking-back ...)) (funcall --cl-scan-and-place-overlays-- (match-string 0) :back)) ((or (and ... ...) (sp--looking-at ...) (looking-at ...) (and ... ...)) (funcall --cl-scan-and-place-overlays-- (match-string 0))) ((or (sp--looking-back ...) (sp--looking-back ...) (and ... ...)) (funcall --cl-scan-and-place-overlays-- (match-string 0) :back)) (sp-show-pair-overlays (sp-show--pair-delete-overlays)))))) (set-match-data save-match-data-internal (quote evaporate)))
  (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- (function (lambda (match &optional back) (let ... ...)))) (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside ...)) match) (cond ((and ... ... ... ...) (funcall --cl-scan-and-place-overlays-- ... :back)) ((or ... ... ... ...) (funcall --cl-scan-and-place-overlays-- ...)) ((or ... ... ...) (funcall --cl-scan-and-place-overlays-- ... :back)) (sp-show-pair-overlays (sp-show--pair-delete-overlays)))))) (set-match-data save-match-data-internal (quote evaporate))))
  (let ((case-fold-search nil)) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- (function (lambda ... ...))) (let* ((pair-list ...) (opening ...) (closing ...) (allowed ...) match) (cond (... ...) (... ...) (... ...) (sp-show-pair-overlays ...))))) (set-match-data save-match-data-internal (quote evaporate)))))
  (if case-fold-search (let ((case-fold-search nil)) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- (function ...)) (let* (... ... ... ... match) (cond ... ... ... ...)))) (set-match-data save-match-data-internal (quote evaporate))))) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- (function (lambda ... ...))) (let* ((pair-list ...) (opening ...) (closing ...) (allowed ...) match) (cond (... ...) (... ...) (... ...) (sp-show-pair-overlays ...))))) (set-match-data save-match-data-internal (quote evaporate)))))
  (progn (if case-fold-search (let ((case-fold-search nil)) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- ...) (let* ... ...))) (set-match-data save-match-data-internal (quote evaporate))))) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- (function ...)) (let* (... ... ... ... match) (cond ... ... ... ...)))) (set-match-data save-match-data-internal (quote evaporate))))))
  (if show-smartparens-mode (progn (if case-fold-search (let ((case-fold-search nil)) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let ... ... ...)) (set-match-data save-match-data-internal (quote evaporate))))) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-scan-and-place-overlays--) (setq --cl-scan-and-place-overlays-- ...) (let* ... ...))) (set-match-data save-match-data-internal (quote evaporate)))))))
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 200000 t sp-show--pair-function nil idle 0])
```

**Comment by abingham** [comment]
This may help some folks. I was seeing the same problem described in this issue, and it turned out that I had inserted some pairs in my "allowed pairs" list that had `nil` for the second value instead of a string. In my spacemacs config I found this:

```
(eval-after-load 'smartparens
     '(progn
        (sp-pair "(" nil :actions :rem)
        (sp-pair "[" nil :actions :rem)
        (sp-pair "'" nil :actions :rem)
        (sp-pair "\"" nil :actions :rem)))
```

By removing this, I made the problem go away.

I'm about 99.999% (scientifically measured) sure I added this on someone's advice in order to address some other problem, but I don't remember the details. I haven't noticed any problems from removing this code, so presumably the original problem is fixed.

Anyhow, maybe others who are experiencing this problem have done the same thing I did.

**Comment by swarnendubiswas** [comment]
Thanks for the tip, @abingham. I am using the following snippet from [emacs.stackexchange](http://emacs.stackexchange.com/questions/26912/smartparens-do-not-insert-parenthesis-pair-when-point-is-at-the-beginning-of-wo)

```
  (sp-pair "(" nil :unless '(sp-point-before-word-p))
  (sp-pair "[" nil :unless '(sp-point-before-word-p))
  (sp-pair "{" nil :unless '(sp-point-before-word-p))
  (sp-local-pair 'latex-mode "$" nil :unless '(sp-point-before-word-p))
```

I will check whether removing it solves the issue.

**Comment by w9** [comment]
For anyone wondering, the snippet @abingham mentioned is likely from:

https://github.com/syl20bnr/spacemacs/issues/6144#issuecomment-251979196

and it's so that you can disable commonly pairs except `{}` (since for a lot of languages they are used as multi-line block delimiters and and it's actually useful in a lot of cases.)

However that snippet somehow removes (`:rem`) too much from whatever under the hood and causes problems. The following alternative should serve the same purpose without breaking things:

```
  (eval-after-load 'smartparens
    '(progn
       (sp-pair "(" nil :actions '(:rem insert))
       (sp-pair "[" nil :actions '(:rem insert))
       (sp-pair "'" nil :actions '(:rem insert))
       (sp-pair "\"" nil :actions '(:rem insert))
       (sp-pair "{" nil :post-handlers '(:add ("||\n[i]" "RET")))
       )
    )
```

**Comment by Fuco1** [comment]
@abingham is most likely correct.  There was a bug (#932) with `:rem` only removing the  setting but not updating the cached per-buffer data structures which caused some inconsistencies you can see

    sp--get-closing-regexp((("\\\\(" . "\\\\)") ("\\(" . "\\)") ("\\{" . "\\}") ("(") ("[")))

The last two pairs have no closing pairs defined.

However I cannot reproduce the aboce situation so I'm not sure if the fix for #932 fixes this problem as well.

The issue in OP @swarnendubiswas was having is probably due to the fact that `$` was never defined before and so the second argument `nil` had nothing to default to.  I will add a check and a sensible error for this case.
