### ISSUE TITLE
Issue with deleting region of whitespaces.

### ISSUE THREAD

**Issue by Ailrun** [Fuco1/smartparens#703]
Is there any good ways to delete region filled with whitespaces,
without deleting wrapped parenthesis?

For example, when we have

``` elisp
(

 |)
```

and mark region from there to

``` elisp
(|

 )
```

here, and type `<backspace>`, the result is

``` elisp
|
```

but what I want is

``` elisp
(|)
```

However, when I mark region in reverse direction, i.e.

``` elisp
(|

 )
```

mark there to

``` elisp
(

 |)
```

here, and type `<backspace>`, it just delete whitespaces, so in this case, the result is actually what I want.

``` elisp
()
```

I think this is the problem of advise of `backward-delete-char` that use `sp-delete-pair`,
since `backward-delete-char` takes care about `use-region` state, where `sp-delete-pair` does not.

Is there any customizable variable for this situation? Does this issue occurs because of my own ignorance?

I'm waiting your answer, thank you.

**Comment by Ailrun** [comment]
P.S. in `smartparens-strict-mode`, `<backspace>` key can't delete any region at all. Is that behavior intended? If it isn't, is there any plan to fix it?

**Comment by Fuco1** [comment]
I can't repro this.  In both strict and nonstrict modes it leaves the parens intact with region selected in either way.

What version of emacs/smartparens do you use?

**Comment by Ailrun** [comment]
I use emacs 25.1 and smartparen 20170129.956 in melpa.

**Comment by Ailrun** [comment]
When I turn off smartparens-mode, deletion works well.

My emacs settings use

1. `delete-active-region` is `t`. (probably default)
2. `sp-autodelete-pair, closing-pair, openinh-pair` are `t`.
3. Use company mode.
4. Problem ocurrs major modes including `emacs-lisp-mode`.

**Comment by Ailrun** [comment]
When these simple configuration, I can reproduce this issue.

![image](https://cloud.githubusercontent.com/assets/12473268/22574091/078b1d2e-e9f0-11e6-8dc4-c9efb4c6b088.png)

mark it to,

![image](https://cloud.githubusercontent.com/assets/12473268/22574118/441e3d34-e9f0-11e6-95d4-3f01fbac91df.png)

here, and hit `<backspace>`.

![image](https://cloud.githubusercontent.com/assets/12473268/22574111/3713b61e-e9f0-11e6-8269-37ad40ce65ce.png)

**Comment by Ailrun** [comment]
@Fuco1 I try this for vanilla emacs only with `smartparens`, and result is same.

On Windows 10, and Linux(CentOS), with emacs `25.1`, installed version of smartparen is `20170129.956`.

**Comment by Ailrun** [comment]
@Fuco1 Sorry for disturbing you. Is there any progress?

**Comment by Fuco1** [comment]
Not really.  I've switched to Emacs 25 though so I'm slowly going through the issues which were only relevant to that version.  I'll schedule this for the next release since you've asked, I might as well randomly prefer this issue over the others ;D

**Comment by Fuco1** [comment]
Hey @Ailrun I think this might have been fixed in 7a8dff4c6f0eb433c3f2bb92b04b5aac5d06d416 (about 4 months ago).  Can you try to verify this?

**Comment by Ailrun** [comment]
@Fuco1 It still not work. I didn't test it with pure emacs, however, when I test with
```shell
emacs -q --eval "(progn (load-file \"~/.emacs.d/elpa/dash-20180206.2124/dash.elc\") (load-file \"~/.emacs.d/elpa/smartparens-20180306.305/smartparens.elc\") (smartparens-global-mode))"
```
It still delete surrounding parens.

**Comment by Fuco1** [comment]
Are you using `delete-selection-mode`?

**Comment by Ailrun** [comment]
@Fuco1 I don't know what it is, so probably I don't use it (or if it's on by default, I use it, since I don't change anything related with it.)

**Comment by Fuco1** [comment]
It's built-in mode to handle deleting of active regions but I don't know if it is on by default.  Can you try to turn it on (`M-x delete-selection-mode`) and then try the above scenario?

**Comment by Ailrun** [comment]
@Fuco1 I just try it. It's off by default, and even after I turn it on, same issue happens.
I also try after turning it off again, and the result is same.

**Comment by Fuco1** [comment]
I reproduced the problem and pushed a fix.  Thanks for the report!
