### ISSUE TITLE
Navigating in XML files causes Spacemacs to hang

### ISSUE THREAD

**Issue by sampablokuper** [Fuco1/smartparens#770]
I haven't (yet) experienced this issue myself, I just want to note that smartparens has been identified (in [this bug report](https://github.com/syl20bnr/spacemacs/issues/7794) as the likely cause of unresponsive behaviour when editing XML files in Spacemacs.

## Expected behavior

See https://github.com/syl20bnr/spacemacs/issues/7794#issuecomment-301729796 .

## Actual behavior

See https://github.com/syl20bnr/spacemacs/issues/7794#issuecomment-301729796 .

## Steps to reproduce the problem

See https://github.com/syl20bnr/spacemacs/issues/7794#issuecomment-301729796 .

## Backtraces if necessary (`M-x toggle-debug-on-error`)

See https://github.com/syl20bnr/spacemacs/issues/7794#issuecomment-303737328

## Environment & version information

- `smartparens` version:
- Active major-mode:
- Emacs version (`M-x emacs-version`): 24, 25, 26
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Spacemacs
- OS: Windows 7 / Windows 10 / Linux mint ([source](https://github.com/syl20bnr/spacemacs/issues/7794#issuecomment-301769400))

**Comment by Fuco1** [comment]
This will probably be fixed by #756

**Comment by nivaca** [comment]
I can confirm the bug persists today (Melpa 20200324.2147).
Smartparens is unusable with nXML mode. Whenever my point crosses any attribute name, Emacs momentarily hangs.
